version: '3'

services:
  mysql:
    image: mariadb
    container_name: librenms-db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./innodb.cnf:/etc/mysql/conf.d/innodb.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=pwd4librenms
  librenms:
    build: .
    container_name: librenms
    volumes:
      - ./data:/data
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_NAME=root
      - DB_USER=root
      - DB_PASS=pwd4librenms
      - TZ="Europe/Berlin"
      - POLLER=24

